### ISSUE TITLE
Checklist moria change

### ISSUE THREAD

**Issue by plirof2** [plirof2/forms_minedu_requirements#6]
- [ ] -Ελεγχος για webform module
- [ ] -Drupal insert
- [ ] -Phpmyedit drupal insert (OK, Found it....
  Just add the following - with the current node number - into the phpmyedit script
  $opts['page_name']='?q=node/12'; (https://www.drupal.org/node/800496)

Webform modules to try:
- [ ] webform_matrix_component-7.x-4.27.tar.gz
- [ ] dynamic content type?
- [ ] 
- [ ] 
- [ ] https://www.commercialprogression.com/post/drupal-webforms-dynamic-select-boxes-tutorial
- [ ] http://drupal.stackexchange.com/questions/83909/autofilling-fields-based-on-another-field
- [ ] http://drupal.stackexchange.com/questions/111605/how-to-add-form-fields-dynamically-using-webformhttp://drupal.org/developing/modules
- [ ] https://www.drupal.org/project/bean
- [ ] https://www.drupal.org/project/webform_addmore (από εδώ μπορούμε να δούμε πως κρύβουμε/εμφανίζουμε)
- [ ] http://drupal.stackexchange.com/questions/76228/programmatically-creating-a-content-type-with-file-field-in-a-custom-module
- [ ] http://public-action.org/content/drupal-7-field-api-drupal-7-adding-custom-content-type-custom-fields-field-api
- [ ] http://www.sitepoint.com/creating-a-new-drupal-node-type/

https://buildamodule.com/blog/the-correct-way-to-include-files-in-your-drupal-module-learning-from-the-drupal-api
